create extension if not exists "pgcrypto";

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.documentation_pages (
  slug text primary key references public.sub_apps(slug) on delete cascade,
  title text not null,
  summary text not null,
  content text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.media_uploads (
  id uuid primary key default gen_random_uuid(),
  file_name text not null,
  bucket text not null default 'site-media',
  storage_path text not null,
  public_url text not null,
  content_type text,
  size_bytes bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.app_releases (
  id bigint generated by default as identity primary key,
  platform text not null check (platform in ('windows', 'macos', 'linux')),
  version text not null,
  label text not null,
  arch text not null,
  url text not null,
  is_recommended boolean not null default false,
  is_active boolean not null default true,
  published_at date not null default current_date,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(platform, version, arch)
);

drop trigger if exists documentation_pages_set_updated_at on public.documentation_pages;

create trigger documentation_pages_set_updated_at
before update on public.documentation_pages
for each row
execute function public.set_updated_at();

drop trigger if exists app_releases_set_updated_at on public.app_releases;

create trigger app_releases_set_updated_at
before update on public.app_releases
for each row
execute function public.set_updated_at();

alter table public.documentation_pages enable row level security;
alter table public.media_uploads enable row level security;
alter table public.app_releases enable row level security;

drop policy if exists "Public can read documentation pages" on public.documentation_pages;

create policy "Public can read documentation pages"
on public.documentation_pages
for select
using (true);

drop policy if exists "Public can read media uploads" on public.media_uploads;

create policy "Public can read media uploads"
on public.media_uploads
for select
using (true);

drop policy if exists "Public can read app releases" on public.app_releases;

create policy "Public can read app releases"
on public.app_releases
for select
using (is_active = true);

insert into storage.buckets (id, name, public)
values ('site-media', 'site-media', true)
on conflict (id) do update
set public = excluded.public;

insert into public.app_releases (
  platform,
  version,
  label,
  arch,
  url,
  is_recommended,
  is_active,
  published_at,
  sort_order
)
values
  (
    'windows',
    '0.1.0',
    'Windows installer',
    'x64',
    'https://github.com/AdeelTahir-SE/DawnDesk/releases/download/v0.2.0/dawndesk_0.1.0_x64_en-US.msi',
    true,
    true,
    '2026-06-01',
    10
  ),
  (
    'macos',
    '0.1.0',
    'macOS build',
    'universal',
    'https://github.com/AdeelTahir-SE/DawnDesk/releases/download/v0.2.0/dawndesk_0.1.0_x64_en-US.msi',
    true,
    false,
    '2026-06-01',
    20
  ),
  (
    'linux',
    '0.1.0',
    'Linux build',
    'x64',
    'https://github.com/AdeelTahir-SE/DawnDesk/releases/download/v0.2.0/dawndesk_0.1.0_x64_en-US.msi',
    true,
    false,
    '2026-06-01',
    30
  )
on conflict (platform, version, arch) do update set
  label = excluded.label,
  url = excluded.url,
  is_recommended = excluded.is_recommended,
  is_active = excluded.is_active,
  published_at = excluded.published_at,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into public.documentation_pages (
  slug,
  title,
  summary,
  content
)
select
  sub_apps.slug,
  sub_apps.name || ' Documentation',
  coalesce(sub_apps.content->>'detail', sub_apps.content->>'summary', ''),
  '## Overview

' || coalesce(sub_apps.content->>'summary', '') || '

## Key features

' || coalesce((
    select string_agg(
      '- **' || coalesce(feature_item.feature->>'title', '') || '**: ' || coalesce(feature_item.feature->>'copy', ''),
      E'\n'
      order by feature_item.ordinality
    )
    from jsonb_array_elements(
      coalesce(sub_apps.content->'features', '[]'::jsonb)
    ) with ordinality as feature_item(feature, ordinality)
  ), '') || '

## Workflow

' || coalesce((
    select string_agg(
      workflow_item.ordinality::text || '. ' || coalesce(workflow_item.step #>> '{}', ''),
      E'\n'
      order by workflow_item.ordinality
    )
    from jsonb_array_elements(
      coalesce(sub_apps.content->'workflow', '[]'::jsonb)
    ) with ordinality as workflow_item(step, ordinality)
  ), '') || '

```mermaid
flowchart TD
  Open[Open workspace] --> Work[Complete focused work]
  Work --> Save[Save output]
  Save --> Reuse[Reuse in DawnDesk]

  ```
  '
  from public.sub_apps as sub_apps
on conflict (slug) do update set
title = excluded.title,
summary = excluded.summary,
content = excluded.content,
updated_at = now();